[package]
name = "musicplayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.16.0"
sndfile = "0.1.1"
ncurses = {version = "5.101.0", features = ["wide"]}
pausable_clock = "1.0.1"
json = "*"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
